version: "3.0"
services:
  bot:
    image: registry.aspc.me/aspcartman/buddy-bot
    restart: unless-stopped
    labels:
      traefik.enable: 'true'
      traefik.backend: buddy-bot
      traefik.frontend.rule: Host:buddy-bot.aspc.me
      traefik.port: '8080'
      traefik.docker.network: traefik_default
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true